### ISSUE TITLE
Generazione mappe http://www.geodati.fmach.it/italia_osm.html

### ISSUE THREAD

**Issue by sorcrosc** [lucadelu/ital.img#10]
Le mappe su http://www.geodati.fmach.it/italia_osm.html non si aggiornano da luglio a quanto pare

**Comment by lucadelu** [comment]
l'aggiornamento è in esecuzione se tutto va bene riattivo il cronjob

**Comment by lucadelu** [comment]
Il problema è stato risolto da giorni

**Comment by sorcrosc** [comment]
grazie Luca
