### ISSUE TITLE
openmtbmap_it_srtm.zip

### ISSUE THREAD

**Issue by thegithubr** [lucadelu/ital.img#5]
Segnalo che l'indirizzo ftp://ftp5.gwdg.de/pub/misc/openstreetmap/openmtbmap/contourlines/openmtbmap_it_srtm.zip non è più raggiungibile, rendendo impossibile l'utilizzo di ital.img

Saluti

**Comment by lucadelu** [comment]
il nuovo url è http://geodati.fmach.it/gfoss_geodata/osm/output_osm_srtm/openmtbmap_it_srtm.zip, risolto con il commit f452f78
