### ISSUE TITLE
Ricerca indirizzi mappe Garmin non funzionante

### ISSUE THREAD

**Issue by sorcrosc** [lucadelu/ital.img#6]
Con mappa (delle Marche) scaricata dal sito http://www.geodati.fmach.it/italia_osm.html su Nuvi 610 non funziona la ricerca per indirizzo (non trova nessuno stato) ne per città (nessuna città).

Vedo che lo script fa due passaggi con mkgmap, il primo dove vengono passate tutte le opzioni ed un secondo per unione dei file .img
Ho fatto delle prove con mkgmap ultima versione e la mappa (il file gmapsupp.img) viene già creata al primo passaggio e con questa la ricerca funziona. Il secondo passaggio sembra inutile e crea una mappa senza indice a quanto pare.

**Comment by sorcrosc** [comment]
Avrei intenzione di aggiornare script, stili e tutto quanto. Pensavo di fare una pull request (mai fatta ma dovrei cavarmela), che ne dici? Senza impegno.
Pensi di poter aggiornare mkgmap all'ultima versione? Serve java 8.

PS. Sto cercando di aiutare una persona che si sta dando da fare per mappare la sua città allo scopo di usare osm nel suo lavoro di autista 118. Ho provato le mappe di tutti i fornitori che ho trovato ma non sono adatte per l'Italia perché hanno tutte la ricerca che funziona solo se si inserisce il nome via esatto.

Lorenzo

**Comment by lucadelu** [comment]
@sorcrosc sarebbe una bellissima cosa, ho appena aggiornato lo script di installazione all'ultima versione disponibile di mkgmap e splitter.

Se puoi fai un nuovo branch e fai le modifiche li, magari prima solo script e dopo gli stili

**Comment by sorcrosc** [comment]
Grazie Luca.
Intanto ho fatto pratica con questo aggiustamento che dovrebbe risolvere il problema segnalato.

Hai già aggiornato i programmi sul server? Perché ho provato a scaricare una mappa per vedere che descrizioni riportava ma non viene proprio riconosciuta dal Garmin. Probabile che con questo aggiustamento tornano a funzionare ma è comunque necessario rivedere qualche opzione.

**Comment by lucadelu** [comment]
Grazie a te Lorenzo,

ho apportato le modifiche, non capisco bene perchè rimuovendo quelle opzione e spostando index dopo debba funzionare, tu lo hai testato?

Comunque stanotte dovrebbe girare con le tue impostazioni e vediamo cosa succede.

**Comment by lucadelu** [comment]
Allora il processo sembra essere andato a buon fine, puoi provare le mappe? se funziona accetto la pull request...

**Comment by sorcrosc** [comment]
No, a causa delle variabili non settate i campi descrittivi delle mappe rimangono vuoti e le mappe non sono lette dal Garmin.
Aspetta che sistemo e ritesto tutte le funzionalità dello script, poi faccio altra pr.

**Comment by lucadelu** [comment]
Ciao, si sembra funzionare bene, prima di approvare la vecchia pull request ho aperto una review per un'opzione che rimuovi, ma che forse potrebbe servire. Potresti controllare?

Per la nuova pull request vorrei prima approvare l'altra e poi mi guardo anche quella.

**Comment by sorcrosc** [comment]
Scusa, cosa intendi per review? A quale opzione ti riferisci?

**Comment by lucadelu** [comment]
Se guardi la pull request c'è una review, pensavo che arrivasse una mail in automatico. Puoi commentare anche li, è comunque l'opzione "--make-cycleways" nello stile ciclismo

**Comment by sorcrosc** [comment]
Non vedo nessuna richiesta di review. Comunque:
--make-cycleways è una opzione obsoleta e non è più valutata. Per sicurezza ho chiesto conferma in mailing list: http://www.mkgmap.org.uk/pipermail/mkgmap-dev/2018q2/028585.html

Rimane valida --make-opposite-cycleways, che crea le cycleway artificiali dove necessario perché le bici possono andare in contro senso, ovvero dove presente oneway:bicycle=no oppure cycleway=opposite_lane/track.
Questa opzione è presente per la mappa ciclismo. Si potrebbe valutare se metterla anche per le mappe normali che sono comunque usabili in modalità bicicletta su Garmin. Faccio una prova ed eventualmente la aggiungo con la pull per lo stile.

**Comment by lucadelu** [comment]
Ok, perfetto allora accetto la prima pull request e poi guardo la seconda :+1:

**Comment by sorcrosc** [comment]
Spero che non hai messo un'altra review perché non la vedo :)

Ti segnalo anche che i file pbf delle regioni non sono aggiornati, i dati sono vecchi. Gli osm.bz2 e Garmin invece sembrano aggiornati

**Comment by sorcrosc** [comment]
Chiudo questa in quanto la ricerca indirizzi era sistemata.
Altra pr ancora in attesa #9
